"""Build the ATT&CK coverage matrix.

Two metrics, and only two, are treated as first-class:

* **coverage attempted** — a *compiled, deployable* detection is mapped to the
  technique. Writing a Sigma file is not enough; if the compiler skipped it, it
  does not count. This is the number most portfolios inflate.
* **coverage validated** — an atomic for the technique actually caused a
  detection to fire. This is the number that is usually missing entirely.

The delta between them (``validation_gap``) is the single most honest figure in
the repo, so it is surfaced everywhere.
"""

from __future__ import annotations

from pathlib import Path

from .models import (
    CoverageMatrix,
    CoverageSummary,
    TechniqueCoverage,
    ValidationResult,
    WazuhRule,
)
from .utils import DATA_DIR, read_yaml

_SCOPE = DATA_DIR / "mappings" / "attack_scope.yaml"


def _norm(technique_id: str) -> str:
    """Normalise a technique id so a rule tagged with a sub-technique's parent
    still counts. e.g. a rule tagged ``T1218`` covers scope entry ``T1218.005``
    only if explicitly tagged; we do not auto-roll-up parents to children.
    Sub-technique tags DO satisfy their exact scope entry."""
    return technique_id.strip().upper()


def build_coverage(
    compiled_rules: list[WazuhRule],
    validation: list[ValidationResult],
    scope_path: str | Path = _SCOPE,
) -> CoverageMatrix:
    scope = read_yaml(scope_path)

    # technique -> compiled rule ids that claim it
    rules_by_tech: dict[str, list[str]] = {}
    for rule in compiled_rules:
        for tid in rule.mitre_ids:
            rules_by_tech.setdefault(_norm(tid), []).append(str(rule.rule_id))

    # technique -> did any atomic validate it
    validated_tech: set[str] = {
        _norm(v.technique_id) for v in validation if v.validated
    }

    rows: list[TechniqueCoverage] = []
    for tid, meta in scope.items():
        ntid = _norm(tid)
        detection_ids = rules_by_tech.get(ntid, [])
        has_detection = bool(detection_ids)
        # "Validated coverage" means a *mapped* detection actually fired. An
        # atomic that ran without any compiled rule to catch it is not validated
        # coverage — it is a gap. Requiring has_detection here keeps validated
        # <= attempted by construction, so validation_gap is never negative.
        rows.append(
            TechniqueCoverage(
                technique_id=tid,
                technique_name=meta["name"],
                tactic=meta.get("tactic", "unknown"),
                detection_ids=detection_ids,
                has_detection=has_detection,
                validated=has_detection and (ntid in validated_tech),
                atomic_guids=[a["guid"] for a in meta.get("atomics", [])],
            )
        )

    rows.sort(key=lambda r: (r.tactic, r.technique_id))

    summary = CoverageSummary(
        techniques_total=len(rows),
        coverage_attempted=sum(1 for r in rows if r.has_detection),
        coverage_validated=sum(1 for r in rows if r.validated),
    )
    return CoverageMatrix(rows=rows, summary=summary)


# --------------------------------------------------------------------------- #
# Rendering
# --------------------------------------------------------------------------- #
def render_markdown(matrix: CoverageMatrix) -> str:
    s = matrix.summary
    lines = [
        "# ATT&CK Coverage Matrix",
        "",
        "> Auto-generated by `socrepo coverage`. Do not edit by hand.",
        "",
        "## Summary",
        "",
        f"- **Techniques in scope:** {s.techniques_total}",
        f"- **Coverage attempted:** {s.coverage_attempted}/{s.techniques_total} "
        f"({s.attempted_pct}%) — a compiled, deployable detection exists",
        f"- **Coverage validated:** {s.coverage_validated}/{s.techniques_total} "
        f"({s.validated_pct}%) — an atomic actually made a detection fire",
        f"- **Validation gap:** {s.validation_gap} technique(s) have a detection "
        "that has never been proven to fire",
        "",
        "## Per-technique",
        "",
        "| Tactic | Technique | Name | Detection | Attempted | Validated |",
        "|---|---|---|---|:--:|:--:|",
    ]
    for r in matrix.rows:
        det = ", ".join(r.detection_ids) if r.detection_ids else "—"
        lines.append(
            f"| {r.tactic} | {r.technique_id} | {r.technique_name} | {det} | "
            f"{'✅' if r.has_detection else '❌'} | "
            f"{'✅' if r.validated else '❌'} |"
        )
    lines += [
        "",
        "Legend: **Attempted** = a compiled detection is mapped to the "
        "technique. **Validated** = an Atomic Red Team test caused that "
        "detection to fire. A ✅/❌ row (attempted but not validated) is a "
        "detection you cannot yet trust.",
        "",
    ]
    return "\n".join(lines)
